spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql205.ccidazbyqjzz.ap-northeast-2.rds.amazonaws.com:3306/final?serverTimezone=UTC
    username: bit
    password: bit
    
mybatis:
  mapper-locations: com/bitcamp/orl/**/mapper/**.xml
    
server:
  port: 8083
  
