
--1.
CREATE TABLE CONTACT (

    PIDX NUMBER(5) CONSTRAINT CONTACT_PIDX_PK PRIMARY KEY,
    NAME VARCHAR2(10) CONSTRAINT CONTACT_NAME_NN NOT NULL,
    PHONENUMBERM VARCHAR2(20) CONSTRAINT CONTACT_PN_NN NOT NULL,
    ADDRESS VARCHAR2(20) DEFAULT 'NON' CONSTRAINT CONTACT_AD_NN NOT NULL,
    EMAIL VARCHAR2(20) DEFAULT 'NON' CONSTRAINT CONTACT_EM_NN NOT NULL, 
    FTYPE VARCHAR2(4) CONSTRAINT CONTACT_F_CK CHECK (FTYPE IN('UNIV', 'COM', 'CAFE')) NOT NULL,

    MAJOR VARCHAR2(10),
    GRADE NUMBER(1),
    CNAME VARCHAR2(10),
    DNAME VARCHAR2(10),
    DGRADE VARCHAR2(10),
    TNAME VARCHAR2(20),
    NICKNAME VARCHAR2(20)
    
);

--2.
