
--#1.
--#2.

--1.
CREATE TABLE MEMBER (

    IDX NUMBER(4) CONSTRAINT MEMBER_IDX_PK PRIMARY KEY,
    ID VARCHAR2(20) CONSTRAINT MEMBER_ID_NN NOT NULL,
    NAME VARCHAR2(20) CONSTRAINT MEMBER_NAME_NN NOT NULL,
    PW VARCHAR2(20) CONSTRAINT MEMBER_PW_NN NOT NULL,
    PNAME VARCHAR2(20),
    JDATE DATE DEFAULT SYSDATE 
    
);


--2.
CREATE INDEX MEMBER_INDEX
ON MEMBER(NAME);


--3.
CREATE VIEW MEMBER_VIEW
AS
SELECT ID, NAME, PNAME
FROM MEMBER;

